name: Build PDF

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: false

jobs:
  build-pdf:
    uses: kolosovpetro/github-latex-template/.github/workflows/build-pdf-template.yml@main
    with:
      file_name: 'FiniteDifferenceOfOddPowerIsDivisibleBy6'
      enable_patch_version: false
      runs_on: 'ubuntu-latest'
      workflow_name: 'Build PDF'
      build_assets_path: |
        src/FiniteDifferenceOfOddPowerIsDivisibleBy6.tex
        src/FiniteDifferenceOfOddPowerIsDivisibleBy6.bbl
        src/FiniteDifferenceOfOddPowerIsDivisibleBy6.bib
        src/sections
      working_directory_for_latex: 'src'
